// Shared data extracted verbatim from ../index.html (desktop app) - do not edit by hand.
// Contains: TONE, FMT, LEN_AR, LEN_EN, PRESETS, AI_TOOLS
const TONE = {
  pro:['احترافي ورسمية','professional and formal'],
  friendly:['ودّي وقريب','friendly and approachable'],
  edu:['تعليمي مبسّط','educational and easy to understand'],
  creative:['إبداعي وملهم','creative and inspiring'],
  concise:['مختصر ومباشر','concise and direct'],
  sales:['مقنع وتسويقي','persuasive and marketing-oriented'],
  sci:['علمي دقيق','scientific and precise'],
  academic:['أكاديمي ودقيق الاستشهاد','academic and rigorously cited'],
  witty:['ساخر ذكي ولطيف','witty, humorous and light-hearted'],
  motivate:['تحفيزي وملهِم','motivational and inspiring'],
  literary:['أدبي شاعري','literary and poetic'],
  convo:['حواري مهذّب','conversational and polite'],
  doc:['توثيقي وتقريري','documentary and report-like'],
  optimistic:['متفائل','optimistic'],
  playful:['مرح وخفيف','playful and light'],
  empathy:['متعاطف ودود','empathetic and supportive'],
  bold:['جريء وحاسم','bold and decisive']
};

const FMT = {
  md:['Markdown','Markdown'], bullets:['قائمة نقطية','bullet points'], table:['جدول','table'],
  json:['JSON صالح فقط','valid JSON only'], code:['كود برمجي','code'], para:['فقرات نصية','paragraphs'],
  img:['صورة مولّدة أو وصف صورة دقيق جاهز للتوليد','a generated image, or a precise image-ready description'],
  html:['صفحة HTML جاهزة مع CSS','a ready HTML page with CSS'],
  csv:['ملف CSV (قيم مفصولة بفواصل)','a CSV file (comma-separated values)'],
  sql:['استعلام SQL','a SQL query'],
  email:['إيميل جاهز للإرسال','a ready-to-send email'],
  script:['نص/سكربت (سيناريو) مكتوب','a written script / screenplay'],
  slides:['بنية عرض تقديمي شريحة بشريحة','a slide-by-slide presentation outline'],
  pdf:['تقرير رسمي منسّق جاهز للطباعة','a formal, print-ready structured report']
};

const LEN_AR={short:'100–150 كلمة (مختصر دون حشو)',medium:'300–500 كلمة',long:'600–1000 كلمة',deep:'مفصّل وشامل دون حد أقصى'};

const LEN_EN={short:'100–150 words, concise with no filler',medium:'300–500 words',long:'600–1000 words',deep:'comprehensive and detailed with no length cap'};

const PRESETS = [
{name:['✍️ مقال/محتوى','✍️ Article / Content'], set:{
  role:['كاتب محتوى خبير ومحرر لغوي','Expert content writer and copy editor'],
  audience:['قراء مهتمون بموضوع المقال','Readers interested in this topic'],
  tone:['pro'], fmt:['md'], length:'long',
  constraints:['ابدأ بجملة خطاف قوية\nاستخدم عناوين فرعية واضحة\nأضف أمثلة واقعية من الحياة\nاختم بخلاصة عملية ودعوة لاتخاذ إجراء',
               'Start with a strong hook\nUse clear subheadings\nAdd real-life examples\nEnd with an actionable takeaway'],
  avoid:['لا تستخدم مقدمات مكررة مثل "في عالم اليوم"\nلا تختلق إحصاءات أو مصادر\nلا تطنب في المديح',
         'No clichéd intros like "In today\'s world"\nNever invent statistics or sources\nNo empty praise'],
  flags:{ask:true,self:true}}},
{name:['💻 برمجة','💻 Coding'], set:{
  role:['مهندس برمجيات خبير يكتب كودًا نظيفًا وموثوقًا','Senior software engineer writing clean, reliable code'],
  audience:['مطوّرون يبقون الكود','Developers who will maintain the code'],
  tone:['sci'], fmt:['code','md'], length:'medium',
  constraints:['اشرح المفاجئات أولًا بإيجاز ثم قدّم الكود\nاكتب تعليقات توضيحية داخل الكود\nاذكر المكتبات المستخدمة\nاقترح اختبارات للدالة',
               'Briefly explain the approach, then give the code\nAdd clarifying comments in the code\nList the libraries used\nSuggest tests for the function'],
  avoid:['لا تعطِ كودًا غير مُختبَر نظريًا\nلا تتجاهل معالجة الأخطاء\nلا تستخدم مكتبات متوقفة عن الدعم',
         'Do not return theoretically untested code\nDo not skip error handling\nNo deprecated libraries'],
  flags:{ask:true,cot:true,self:true}}},
{name:['📊 تحليل بيانات','📊 Data Analysis'], set:{
  role:['محلل بيانات استشاري يستخرج الرؤى من الأرقام','Consulting data analyst who extracts insights from numbers'],
  audience:['فريق الإدارة وصناع القرار','Leadership and decision makers'],
  tone:['sci'], fmt:['md','table'], length:'medium',
  constraints:['اعرض الأرقام في جدول تجميعي\nاستخرج 3 رؤى رئيسية مع تفسير كل منها\nميّز بين الارتباط والسببية\nاختم بتوصيات قابلة للتنفيذ',
               'Present the numbers in a summary table\nExtract 3 key insights and explain each\nDistinguish correlation from causation\nEnd with actionable recommendations'],
  avoid:['لا تخلط بين المتوسط والوسيط\nلا تقدم استنتاجات بلا دليل',
         'Do not confuse mean with median\nNo conclusions without evidence'],
  flags:{ask:true,cot:true,self:true}}},
{name:['🎯 تسويق وإعلان','🎯 Marketing'], set:{
  role:['مدير تسويق رقمي يكتب نصوصًا إعلانية فائقة الإقناع','Digital marketing manager writing highly persuasive ad copy'],
  audience:['عملاء محتملون لا يعرفون المنتج','Potential customers who do not know the product'],
  tone:['sales'], fmt:['bullets'], length:'medium',
  constraints:['ابدأ بمشكلة العميل وليس بالمنتج\nاستخدم إثباتًا اجتماعيًا أو رقمًا داعمًا\nاكتب 3 نسخ إعلانية بطول مختلف\nأضف CTA واضحًا',
               'Start with the customer problem, not the product\nUse social proof or a supporting number\nWrite 3 ad variants of different lengths\nAdd a clear CTA'],
  avoid:['لا تستخدم وعودًا مبالغًا فيها\nلا تستخدم عبارات فارغة مثل "جودة عالية"',
         'No exaggerated promises\nNo empty phrases like "high quality"'],
  flags:{self:true,few:true}}},
{name:['📚 تلخيص','📚 Summarize'], set:{
  role:['محضر ملخصات دقيق يلتقط الأفكار الجوهرية فقط','Precise summarizer capturing only the core ideas'],
  audience:['قارئ يريد الفكرة خلال دقيقة','A reader who wants the idea in one minute'],
  tone:['concise'], fmt:['bullets','md'], length:'short',
  constraints:['لخّص في 5 نقاط كحد أقصى\nحافظ على المصطلحات الأساسية\nأضف سطرًا واحدًا للخلاصة في الأعلى',
               'Summarize in at most 5 bullet points\nKeep the key terms\nAdd a one-line takeaway at the top'],
  avoid:['لا تضف آراءك الشخصية\nلا تكرر نفس الفكرة بصياغات مختلفة',
         'Do not add personal opinions\nDo not repeat the same idea in different words'],
  flags:{ask:true,self:true}}},
{name:['🗺️ خطة ودراسة','🗺️ Study Plan'], set:{
  role:['مدرّب وخبير في تخطيط المسارات والتعلم المُحكَم','Coach and expert in planning structured learning paths'],
  audience:['مبتدئ يريد خطة واقعية قابلة للتنفيذ','A beginner wanting a realistic, doable plan'],
  tone:['edu'], fmt:['table','md'], length:'long',
  constraints:['قسّم الخطة إلى مراحل زمنية واضحة\nحدد مدة كل مرحلة ومخرجها\nأضف معيار نجاح لكل مرحلة\nأضف بديلًا في حال تعذر الالتزام',
               'Split the plan into clear time phases\nSet the duration and output of each phase\nAdd a success criterion per phase\nAdd a fallback if the schedule slips'],
  avoid:['لا تعطِ جدولًا غير واقعي\nلا تترك مرحلة بلا مخرج ملموس',
         'No unrealistic schedule\nNo phase without a tangible output'],
  flags:{ask:true,cot:true,self:true}}},
{name:['🌐 ترجمة احترافية','🌐 Translation'], set:{
  role:['مترجم محترف متمرس في الترجمة التحريرية لا الحرفية','Professional translator specialized in transcreation, not literal translation'],
  audience:['قارئ أصلي في اللغة الهدف','A native reader of the target language'],
  tone:['pro'], fmt:['para'], length:'medium',
  constraints:['ترجم المعنى لا الكلمات\nحافظ على نبرة النص الأصلية\nوضّح أي تمثيل ثقافي غير مفهوم',
               'Translate meaning, not words\nKeep the tone of the original\nClarify cultural references that do not carry over'],
  avoid:['لا تترجم الأسماء والعلامات التجارية\nلا تضف معلومات غير موجودة',
         'Do not translate proper names or brands\nDo not add missing information'],
  flags:{ask:true,self:true}}},
{name:['📧 كتابة إيميل', '📧 Email writing'], set:{
  role:['خبير تواصل أعمال يكتب رسائل واضحة وموجزة','Business communication expert writing clear, concise messages'],
  audience:['زميل أو عميل مشغول يريد الخلاصة أولًا','A busy colleague or client who wants the point first'],
  tone:['pro','concise'], fmt:['email','para'], length:'short',
  constraints:['ابدأ بهدف الرسالة في السطر الأول\nاجعل طلباتك في نقاط مرقّمة\nاختم بخطوة تالية واحدة واضحة\nحافظ على أقل من 150 كلمة',
               'Open with the purpose in the first line\nPut your asks in numbered bullets\nEnd with one clear next step\nKeep it under 150 words'],
  avoid:['لا تطبل بلا داعٍ\nلا تكتب فقرات طويلة','No flattery without reason\nNo long paragraphs'],
  flags:{ask:true,self:true,direct:true}}},
{name:['📱 منشور سوشيال ميديا','📱 Social media post'], set:{
  role:['صانع محتوى سوشيال يعرف خوارزميات المنصات','Social content creator who knows platform algorithms'],
  audience:['متابعون يمرّون بسرعة في الخلاصة','Followers scrolling fast in the feed'],
  tone:['creative','friendly'], fmt:['bullets'], length:'short',
  constraints:['اكتب 3 نسخ: طويلة، متوسطة، قصيرة\nأضف هاشتاقات مناسبة (5–8)\nابدأ بخطاف في أول سطر\nأضف CTA واضحًا',
               'Write 3 variants: long, medium, short\nAdd 5–8 relevant hashtags\nHook the reader in line one\nAdd a clear CTA'],
  avoid:['لا تستخدم أكثر من 8 هاشتاقات\nلا تشتّت الرسالة','No more than 8 hashtags\nNo mixed message'],
  flags:{self:true,alts:true}}},
{name:['🎬 سكربت فيديو','🎬 Video script'], set:{
  role:['كاتب سكربيبات فيديو يحفظ المشاهد من التشتّت','Video scriptwriter who keeps viewers hooked'],
  audience:['مشاهد لا يتجاوز الثواني الأولى','A viewer who does not survive the first seconds'],
  tone:['creative','playful'], fmt:['script'], length:'medium',
  constraints:['صيغة: خطاف / محتوى / CTA\nاكتب تعليمات المشهد بين قوسين\nجمل قصيرة تناسب القراءة الصوتية\nحدد الزمن التقريبي لكل قسم',
               'Format: hook / content / CTA\nPut stage directions in brackets\nShort sentences suited for voice-over\nAdd approximate timing per section'],
  avoid:['لا تبدأ بمقدمة طويلة\nلا تكتب نصًا يصعب نطقه','No long intro\nNo tongue-twisting lines'],
  flags:{ask:true,cot:false,self:true}}},
{name:['💡 توليد أفكار','💡 Brainstorm'], set:{
  role:['ميسّر ورش تفكير ينتج أفكارًا غير مكرّرة','Workshop facilitator producing non-repetitive ideas'],
  audience:['فريق يحتاج قرارات لا قوائم طويلة','A team that needs decisions, not long lists'],
  tone:['creative','optimistic'], fmt:['bullets','table'], length:'medium',
  constraints:['ولّد 10 أفكار على الأقل مع تقييم جدوى 1–5\nصنّفها: سريعة / متوسطة / طويلة المدى\nاختر أفضل 3 وبرّر اختيارك',
               'Generate at least 10 ideas rated 1–5 for feasibility\nGroup them: quick / medium / long-term\nPick the best 3 and justify'],
  avoid:['لا تكرر الفكرة نفسها بصياغات\nلا تبالغ في التقييم','No rephrased duplicates\nNo inflated ratings'],
  flags:{cot:true,balanced:true,self:true}}},
{name:['🔍 تحليل منافسين','🔍 Competitor analysis'], set:{
  role:['محلل استراتيجي يقارن بإنصاف ويستخلص الفرص','Strategy analyst comparing fairly and extracting opportunities'],
  audience:['صاحب عمل يريد قرارًا لا تقريرًا','A business owner who wants a decision, not a report'],
  tone:['sci','doc'], fmt:['table','md'], length:'long',
  constraints:['قارن في جدول: الأسعار، المزايا، الجمهور، نقاط الضعف\nاستخرج 3 فجوات يمكنك استغلالها\nاختم بخطة تميّز قابلة للتنفيذ',
               'Compare in a table: pricing, strengths, audience, weaknesses\nExtract 3 gaps you can exploit\nEnd with an executable differentiator plan'],
  avoid:['لا تفترض أرقامًا غير مؤكدة\nلا تتحيز لطرف','No unverified numbers\nNo bias toward one side'],
  flags:{ask:true,sources:true,alts:true}}},
{name:['🛍️ أوصاف منتجات SEO','🛍️ Product descriptions'], set:{
  role:['كاتب أوصاف تجارة إلكترونية يبيع بأسلوب نظيف','E-commerce copywriter who sells without sounding spammy'],
  audience:['متسوّق متردد يقارن قبل الشراء','A hesitant shopper comparing before buying'],
  tone:['sales','friendly'], fmt:['para','bullets'], length:'medium',
  constraints:['عنوان فرعي + فقرة + 4 نقاط مزايا + سطر CTA\nادمج الكلمات المفتاحية بشكل طبيعي\nاخاطب الفائدة لا الصفة',
               'Subheadline + paragraph + 4 benefit bullets + CTA line\nWork keywords in naturally\nSell the benefit, not the feature'],
  avoid:['لا تبالغ في الوعود\nلا تكرر الكلمة المفتاحية','No exaggerated promises\nNo keyword stuffing'],
  flags:{self:true,direct:true}}},
{name:['👨‍🏫 شرح مفهوم معقد','👨‍🏫 Explain a concept'], set:{
  role:['مدرّب يشفّر المفاهيم الصعبة إلى صور بسيطة','Teacher who decodes hard concepts into simple pictures'],
  audience:['مبتدئ بلا خلفية في الموضوع','A beginner with no background in the topic'],
  tone:['edu','empathy'], fmt:['para','bullets'], length:'medium',
  constraints:['ابدأ بتشبيه من الحياة اليومية\nقدّم مثالًا ملموسًا ثم القاعدة\nاختبر الفهم بسؤالين في النهاية',
               'Start with an everyday analogy\nGive a concrete example, then the rule\nCheck understanding with two questions'],
  avoid:['لا تقفز فوق الأساسيات\nلا تستخدم مصطلحات بلا شرح','No skipping the basics\nNo unexplained terms'],
  flags:{simple:true,cot:true,self:true}}},
{name:['💬 رد على عميل','💬 Customer reply'], set:{
  role:['أخصائي دعم يحول الشكوى إلى ولاء','Support agent turning complaints into loyalty'],
  audience:['عميق غاضب يريد حلًا لا أعذارًا','An upset customer who wants a fix, not excuses'],
  tone:['empathy','pro'], fmt:['para'], length:'short',
  constraints:['اعترف بالمشكلة أولًا ثم الحل والجدول الزمني\nاعرض خطوتين واضحتين\nاختم بتعويض مناسب إن لزم',
               'Acknowledge first, then the fix and timeline\nOffer two clear steps\nClose with a fair remedy if needed'],
  avoid:['لا تلقِ اللوم على العميل\nلا تعتذر أكثر من مرة واحدة','Do not blame the customer\nDo not apologize more than once'],
  flags:{ask:true,self:true,direct:true}}}
,
{name:['🖼️ توليد صورة','🖼️ Image Generation'], set:{
  role:[''],audience:['',''],tone:[],fmt:[],length:'',constraints:['',''],avoid:['',''],
  flags:{ask:false,cot:false,self:false,few:false}, img:true}}
];

const AI_TOOLS = [
 {e:'💬', n:['ChatGPT','ChatGPT'],
  d:['أشهر مساعد ذكي من OpenAI للنصوص والصور والتحليل.','The most popular AI assistant from OpenAI for text, images and analysis.'],
  u:'https://chatgpt.com/',
  an:['Open WebUI','Open WebUI'],
  ad:['واجهة مفتوحة المصدر تشغّل النماذج محليًا أو عبر أي مزوّد.','Open-source UI that runs models locally or through any provider.'],
  au:'https://github.com/open-webui/open-webui'},
 {e:'✳️', n:['Claude','Claude'],
  d:['نماذج Anthropic القوية للكتابة والبرمجة والمستندات الطويلة.','Powerful Anthropic models for writing, coding and long documents.'],
  u:'https://claude.ai/',
  an:['LibreChat','LibreChat'],
  ad:['منصّة مفتوحة المصدر تجمع عدة نماذج في واجهة واحدة.','Open-source platform gathering several models in one interface.'],
  au:'https://github.com/danny-avila/LibreChat'},
 {e:'♊', n:['Gemini','Gemini'],
  d:['نماذج Google متعددة الوسائط مدمجة مع خدماتها.','Google multimodal models integrated with its services.'],
  u:'https://gemini.google.com/',
  an:['Jan','Jan'],
  ad:['مساعد مفتوح المصدر يعمل دون إنترنت على جهازك.','Open-source assistant that runs offline on your machine.'],
  au:'https://github.com/janhq/jan'},
 {e:'🎨', n:['Midjourney','Midjourney'],
  d:['أشهر أداة لتوليد الصور الفنية من الوصف النصي.','The most famous tool for generating art from text.'],
  u:'https://www.midjourney.com/',
  an:['Stable Diffusion WebUI','Stable Diffusion WebUI'],
  ad:['توليد صور مجاني مفتوح المصدر يعمل على كرت الشاشة لديك.','Free open-source image generation running on your GPU.'],
  au:'https://github.com/AUTOMATIC1111/stable-diffusion-webui'},
 {e:'💻', n:['GitHub Copilot','GitHub Copilot'],
  d:['مساعد برمجة داخل المحرر يكمل الكود ويقترح الحلول.','An in-editor coding assistant that completes and suggests code.'],
  u:'https://github.com/features/copilot',
  an:['Aider','Aider'],
  ad:['زميل برمجي مجاني مفتوح المصدر يعمل من الطرفية.','Free open-source AI pair programmer that runs in the terminal.'],
  au:'https://github.com/Aider-AI/aider'},
 {e:'🔎', n:['Perplexity','Perplexity'],
  d:['محرك بحث يعطي إجابات مدعومة بالمصادر.','A search engine that answers with cited sources.'],
  u:'https://www.perplexity.ai/',
  an:['Khoj','Khoj'],
  ad:['مساعد شخصي مفتوح المصدر يبحث ويجيب من مصادرك.','Open-source personal assistant that answers from your sources.'],
  au:'https://github.com/khoj-ai/khoj'},
 {e:'🎙️', n:['ElevenLabs','ElevenLabs'],
  d:['تحويل النص إلى كلام واقعي بلهجات متعددة.','Realistic text-to-speech with many voices and accents.'],
  u:'https://elevenlabs.io/',
  an:['Coqui TTS','Coqui TTS'],
  ad:['توليد صوت مجاني مفتوح المصدر يعمل محليًا.','Free open-source speech synthesis running locally.'],
  au:'https://github.com/coqui-ai/TTS'},
 {e:'🎬', n:['Sora','Sora'],
  d:['توليد فيديو قصير من وصف نصي.','Short video generation from a text description.'],
  u:'https://sora.com/',
  an:['LTX-Video','LTX-Video'],
  ad:['نموذج فيديو مفتوح المصدر سريع التوليد على كرت الشاشة.','Open-source video model that generates fast on your GPU.'],
  au:'https://github.com/Lightricks/LTX-Video'}
];
